---
title: "assignment2"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(tidycensus)
library(sf)
library(tigris)
library(leaflet)
library(mapview)
library(scales)
```

## R Markdown

```{r}
census_api_key('017d1d5b27f8be3da8aa03709590af32410b9007', install = T)
```


```{r}
acs19var = load_variables(2019, "acs5")
acs19var
```

```{r}
il19 = get_acs(
  geography = "tract", 
  variables = c(
    medincome = "B19013_001",
    totalpop = "B02001_001",
    white_alone = "B02001_002",
    black_alone = "B02001_003",
    asian_alone = "B02001_004"
  ),
  state = "IL",
  year = 2019,
  output = "wide"
)

il19 <- il19 %>% mutate(
  pct_white = white_aloneE / totalpopE,
  pct_black = black_aloneE / totalpopE,
  pct_asian = asian_aloneE / totalpopE
)

iltracts <- tigris::tracts(state='17', year=2019, cb=TRUE)

cook_tracts_acs <- 
  iltracts %>% 
  left_join(il19 %>% select(GEOID, pct_white, totalpopE, medincomeE)) %>% 
  filter(COUNTYFP == '031') #cook

ilcountysub <- tigris::county_subdivisions(state=17, county=31, cb=TRUE)
chicago <- ilcountysub %>% filter(NAME == "Chicago") %>% select(region=NAME)

chicago_tracts_acs <- cook_tracts_acs %>% st_intersection(
  chicago
)
```

```{r}
joined = cook_tracts_acs

label_str <- str_glue("<strong>Tract %s</strong><br>White Alone (Pct): %s<br/>")
labels <- sprintf(label_str,
                joined$NAME,
                percent(joined$pct_white, accuracy = .1)) %>% 
  lapply(htmltools::HTML)
```


```{r}
mapview(chicago_tracts_acs, alpha=.05, col.regions='green') +
  mapview(chicago)
```


First leaflet map

```{r}
leaflet() %>%
  addTiles() 

leaflet() %>%
  addTiles() %>% addPolygons(data = chicago_tracts_acs)
```



```{r}

```

