---
title: "Part 3"
author: "Alexis Kwan"
output: 
  html_document:
    code_folding: hide
    df_print: paged
    theme: sandstone
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE)
library(tidyverse)
library(lubridate)
library(tidymodels)
library(lubridate)
library(parsnip)
library(discrim)
library(cmfproperty)
```

```{r setup, include=FALSE}
con <- DBI::dbConnect(RSQLite::SQLite(), "../database/detroit.sqlite")

assessments <- dplyr::tbl(con, 'assessments') %>% collect()
sales <- dplyr::tbl(con, 'sales') %>% collect()
parcels <- dplyr::tbl(con, 'parcels') %>% collect()
```

```{r preprocessing}
#
# Preprocessing
#

foreclosures <- dplyr::tbl(con, 'foreclosures') %>%
  collect() %>%
  select(-prop_addr) %>%
  pivot_longer(!prop_parcelnum, names_to='year', values_to='foreclosed') %>%
  filter(!is.na(foreclosed)) %>%
  distinct()

joined = 
  sales %>%
  mutate(year = year(ymd(sale_date)),
         sale_year = as.factor(year)) %>%
  left_join(assessments, by=c('parcel_num'='PARCELNO', c('year'='year')), suffix = c("", "_assessed")) %>%
  left_join(parcels, by = c('parcel_num'='parcel_number'), suffix = c("", "_parcel")) %>%
  mutate(property_c = as.character(property_c),
         propclass = as.character(propclass)) %>% 
  filter(str_detect(sale_terms, regex("valid arm", ignore_case = TRUE))) %>%
  filter(propclass == 401)

joined_mini = 
  joined %>%
  filter(property_c == 401,
         sale_price >= 2000,
         ASSESSEDVALUE >= 1000,
         str_detect(str_to_lower(sale_terms), 'valid arm')) %>%
  left_join(foreclosures, by=c('parcel_num'='prop_parcelnum', c('sale_year'='year')))

ratios =
  cmfproperty::reformat_data(
    joined_mini,
    sale_col = "sale_price",
    assessment_col = "ASSESSEDVALUE",
    sale_year_col = "year",
  )

stats = calc_iaao_stats(ratios)
```

```{r}
joined_mini =
  joined_mini %>%
  group_by(ward) %>%
  mutate(foreclosure_ward_ratio = sum(foreclosed, na.rm = T)/sum(joined_mini$foreclosed, na.rm = T))

joined_mini
```

