---
title: "Economic Zones"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
library(tidymodels)
library(sf)
library(tigris)
library(tidycensus)
library(janitor)
library(factoextra)
library(cluster)
library(kernlab)
library(dbscan)
```

```{r}
chicago_tracts = read_csv("chicago_tracts.csv") %>%
  mutate(GEOID = as.character(GEOID))
```

```{r}
chicago_tracts_transit =
  read_csv("chicago_tracts_2020_transit_needs_2015_2017_walkability_2020_tif_2021.csv") %>%
  mutate(
    GEOID = as.character(GEOID),
    tract = NAME,
    tif = ref,
    walk_score = TotalScore,
    trans_avail = Mean_trans
  )

tif_exp = read_csv("TIF_Expenditures_2017_2020.csv") %>%
  clean_names() %>%
  rowwise() %>%
  mutate(total_tif_expend = sum(c_across(8:22))) %>%
  group_by(tif_number) %>%
  summarise(total_tif_expend_2017_2020 = sum(total_tif_expend)) %>%
  ungroup()

chicago_tracts_transit_tif =
 chicago_tracts_transit %>% 
  left_join(
    tif_exp,
    by = c("tif"="tif_number"),
    suffix = c("","_tif")
  ) %>%
  mutate(lat = INTPTLAT,
         lon = INTPTLON) %>%
  group_by(GEOID,
           tract,
           Emp_Transi,
           HH_Density,
           lat,
           lon) %>%
  summarise(
    HH_per_acr_med = median(HH_per_acr, na.rm = T),
    emp_mile_med = median(Emp_within, na.rm = T),
    trans_avail_med = median(trans_avail, na.rm = T),
    walk_score_med = median(walk_score, na.rm = T),
    tif_expend_med = median(total_tif_expend_2017_2020, na.rm = T)
  ) %>%
  ungroup()
```


```{r}
vars = load_variables(2020, "acs5", cache = TRUE)
subject_vars = load_variables(2020, "acs5/subject", cache = TRUE)
```

S2503 - FINANCIAL CHARACTERISTICS 
S2506 - FINANCIAL CHARACTERISTICS FOR HOUSING UNITS WITH A MORTGAGE
S2507 - FINANCIAL CHARACTERISTICS FOR HOUSING UNITS WITHOUT A MORTGAGE 

```{r}
# cook_fin_acs = 
#   get_acs(
#     geography = "tract",
#     # table = "S2503",
#     year = 2020,
#     variables = c(
#       cost_per_0_income = "S2503_C01_045",
#       cost_per_no_cash_income = "S2503_C01_046",
#       cost_per_20k_income = "S2503_C01_025",
#       cost_per_35k_income = "S2503_C01_029",
#       cost_per_50k_income = "S2503_C01_033",
#       cost_per_75k_income = "S2503_C01_037",
#       cost_per_75k_plus_income = "S2503_C01_041",
#       household_income = "B25120_001",
#       mean_commute_minutes = "S0802_C04_090"
#     ),
#     state = 17,
#     county = 31,
#     output = 'wide',
#     geometry = T,
#     cache_table = T
#   ) %>%
#   mutate(
#     income_per_cost_0 = 100/cost_per_0_incomeE,
#     income_per_cost_no_cash = 100/cost_per_no_cash_incomeE,
#     income_per_cost_20k = 100/cost_per_20k_incomeE,
#     income_per_cost_35k = 100/cost_per_35k_incomeE,
#     income_per_cost_50k = 100/cost_per_50k_incomeE,
#     income_per_cost_75k = 100/cost_per_75k_incomeE,
#     income_per_cost_75k_plus = 100/cost_per_75k_plus_incomeE
#   )

cook_fin_acs = 
  get_acs(
    geography = "tract",
    # table = "S2503",
    year = 2020,
    variables = c(
      household_income = "B25120_001",
      mean_commute_minutes = "S0802_C04_090"
    ),
    state = 17,
    county = 31,
    output = 'wide',
    geometry = T,
    cache_table = T
  )

cook_acs = get_acs(
  geography = "tract",
  year = 2020,
  variables = c(
    transit_means_tot = "B08119_001",
    transit_public = "B08119_028",
    transit_walked = "B08119_037",
    prop_value_med = "B25097_001"
  ), 
  state = 17,
  county = 31,
  # place = "Chicago city",
  output = 'wide',
  geometry = T,
  cache_table = T
)
```


```{r}
chicago_transit_acs_tif =
  chicago_tracts_transit_tif %>%
  left_join(cook_acs,
            by = c("GEOID" = "GEOID"),
            suffix = c("", "_acs")) %>%
  left_join(cook_fin_acs,
            by = c("GEOID" = "GEOID"),
            suffix = c("", "_fin_acs")) %>%
  select(c("GEOID":"tif_expend_med"),
        c("transit_means_totE":"prop_value_medM"),
        c("household_incomeE":"mean_commute_minutesM"),
        "geometry",
        "lat",
        "lon")
```

```{r}
econ_zone_recipe = 
  recipe(~., data = chicago_transit_acs_tif %>% select(1, 5:23)) %>% 
  step_impute_knn(all_numeric(), neighbors = 3) %>%
  # step_naomit(ecf, total_square_footage, year_built, zoning) %>%
  # step_unknown(all_nominal_predictors()) %>%
  # step_dummy(all_nominal_predictors()) %>%
  step_normalize(all_numeric(), na_rm = T) %>%
  prep()
econ_zone_baked = econ_zone_recipe %>% bake(new_data = NULL)
econ_zone_matrix = econ_zone_baked %>% select(2:18)
head(econ_zone_baked)
```

## DBSCAN

```{r}
dbs =
  tibble(k = 1:9) %>%
  mutate(
    kclust = map(k, ~kmeans(points, .x)),
    tidied = map(kclust, tidy),
    glanced = map(kclust, glance),
    augmented = map(kclust, augment, points)
  )

db = dbscan(econ_zone_matrix, eps = 1, minPts = 10)
db
```

```{r}
chicago_transit_acs_tif %>%
  mutate(db_cluster = db$cluster)
```

```{r}
chicago_transit_acs_tif %>%
  mutate(db_cluster = db$cluster) %>%
  group_by()
```

## K-Means Clustering

```{r}
points = econ_zone_matrix

kclusts =
  tibble(k = 1:9) %>%
  mutate(
    kclust = map(k, ~kmeans(points, .x)),
    tidied = map(kclust, tidy),
    glanced = map(kclust, glance),
    augmented = map(kclust, augment, points)
  )

clusters =
  kclusts %>%
  unnest(cols = c(tidied))

assignments =
  kclusts %>% 
  unnest(cols = c(augmented))

clusterings =
  kclusts %>%
  unnest(cols = c(glanced))

# ggplot(clusterings, aes(k, tot.withinss)) +
#   geom_line() +
#   geom_point()
```

```{r}
fviz_nbclust(econ_zone_matrix, FUN = kmeans, method = "wss")
```


```{r}
fviz_nbclust(econ_zone_matrix, FUN = kmeans, method = "silhouette")
```

```{r}
econ_means = kmeans(points, centers = 2)

fviz_cluster(econ_means, 
             data = points,
             geom="point")
```


```{r}
fviz_cluster(econ_means, 
             data = points %>% select(household_incomeE, trans_avail_med),
             geom="point")
```

```{r}
fviz_cluster(econ_means, 
             data = points %>% select(household_incomeE, tif_expend_med),
             geom="point")
```

## Kernal K-Means Clustering

```{r}
econ_kkmeans = kkmeans(
  as.matrix(points),
  centers = 2,
  kernel = 'rbfdot',
  kpar = list(sigma = 0.005)
)

fviz_cluster(list(data = points, cluster = econ_kkmeans@.Data),
             geom = "point",
             main = "kkmeans") 
```

## GIS Processing

```{r}
chicago_transit_acs_tif_aug =
  chicago_transit_acs_tif %>%
  mutate(means_2 = kmeans(points, centers = 2)$cluster,
         means_3 = kmeans(points, centers = 3)$cluster)
```

```{r}
chicago_transit_acs_tif_aug %>%
  group_by(means_2) %>%
  summarise(hh_income = median(household_incomeE, na.rm = T),
            prop_value = median(prop_value_medE, na.rm = T),
            transit_avail = median(trans_avail_med, na.rm = T),
            walkability = median(walk_score_med, na.rm = T))
```

```{r}
chicago_transit_acs_tif_aug %>%
  group_by(means_3) %>%
  summarise(hh_income = median(household_incomeE, na.rm = T),
            prop_value = median(prop_value_medE, na.rm = T),
            transit_avail = median(trans_avail_med, na.rm = T),
            walkability = median(walk_score_med, na.rm = T))
```

```{r}
chicago_transit_acs_tif_aug =
  chicago_transit_acs_tif_aug %>%
  mutate(
    km_label_1 = case_when(means_2 == 1 ~ "High Development",
                           means_2 == 2 ~ "Low Development"),
    km_label_2 = case_when(
      means_3 == 1 ~ "Low Development",
      means_3 == 2 ~ "Medium Development",
      means_3 == 3 ~ "High Development"
    )
  )
write_csv(chicago_transit_acs_tif_aug, file = "chicago_transit_acs_tif_aug.csv")
```


```{r}
st_write(chicago_transit_acs_tif_aug, "chicago_transit_acs_tif_aug.geojson")
```

```{r}
tif_projects = read_csv("Tax_Increment_Financing__TIF__Annual_Report_-_Projects.csv")
tif_projects_agg = 
  tif_projects %>%
  clean_names() %>%
  filter(ongoing == T) %>%
  group_by(tif_number) %>%
  summarise(total_payments = sum(current_year_payments))
write_csv(tif_projects_agg, file = "tif_projects_agg.csv")
```

```{r}
cluster_spend = read_csv("EconomicClustering_TIF_Projects.csv")
cluster_spend %>%
  group_by(means_3)
```

